import type { Payload } from "payload";

// ─── Type commun ──────────────────────────────────────────────────────────────

type MarkerInput = {
	name: string;
	address: string;
	postalCode: string;
	city: string;
	latitude: number;
	longitude: number;
	phone?: string;
	email?: string;
	website?: string;
	description?: string;
	metadata?: Record<string, unknown>;
};

// ─── Catégories ──────────────────────────────────────────────────────────────

const mapCategories = [
	{
		name: "Centre de Ressources Autisme",
		slug: "cra",
		colorVariant: "blue-ecume" as const,
		iconId: "fr-icon-map-pin-2-fill",
		description:
			"Les CRA sont des structures régionales qui proposent un appui aux professionnels et aux familles concernées par les troubles du spectre autistique.",
		customFields: [
			{
				label: "Pôle Adulte",
				key: "pole-adulte",
				type: "checkbox" as const,
			},
		],
	},
	{
		name: "Maison Départementale des Personnes Handicapées",
		slug: "mdph",
		colorVariant: "green-emeraude" as const,
		iconId: "fr-icon-map-pin-2-fill",
		description:
			"Les MDPH accompagnent les personnes en situation de handicap dans leurs démarches administratives et l'accès aux droits et aides.",
	},
];

// ─── Marqueurs CRA ────────────────────────────────────────────────────────────

const craMarkers: MarkerInput[] = [
	{
		name: "CRA Alsace",
		address:
			"Centre Hospitalier de Rouffach - 27 rue du 4ème RSM - Pavillon 21",
		postalCode: "68250",
		city: "Rouffach",
		latitude: 47.950406,
		longitude: 7.2907,
		phone: "03 89 78 79 64",
		email: "secretariat68@cra-alsace.fr",
		website: "https://cra-alsace.fr/",
		description: "Centre de Ressources Autisme de Grand Est.",
		metadata: { "pole-adulte": true },
	},
	{
		name: "CRA Aquitaine",
		address: "Hôpital Charles Perrens - 146 bis rue Léo Saignat",
		postalCode: "33000",
		city: "Bordeaux",
		latitude: 44.827182,
		longitude: -0.594896,
		phone: "05 33 57 80 49",
		email: "poleadoscra-aquitaine@ch-perrens.fr",
		website: "https://cra.ch-perrens.fr/",
		description: "Centre de Ressources Autisme de Nouvelle-Aquitaine.",
		metadata: { "pole-adulte": false },
	},
	{
		name: "CRA Auvergne",
		address: "CHU Gabriel Mont pied Pôle de Psychiatrie - 58 rue Montalembert",
		postalCode: "63000",
		city: "Clermont-Ferrand",
		latitude: 45.756911,
		longitude: 3.094373,
		phone: "04 73 75 19 48",
		email: "cra-auvergne@chu-clermontferrand.fr",
		website:
			"https://www.chu-clermontferrand.fr/liste-services/le-cra-en-auvergne",
		description: "Centre de Ressources Autisme d'Auvergne-Rhône-Alpes.",
		metadata: { "pole-adulte": true },
	},
	{
		name: "CRA Bourgogne",
		address: "Le Clos des Présidents - 19-21 rue René Coty",
		postalCode: "21001",
		city: "Dijon",
		latitude: 47.298044,
		longitude: 5.067067,
		phone: "03 80 29 54 19",
		email: "cra@crabourgogne.org",
		website: "https://www.crabourgogne.org/",
		description: "Centre de Ressources Autisme de Bourgogne-Franche-Comté.",
		metadata: { "pole-adulte": false },
	},
	{
		name: "CRA Bretagne",
		address: "Unité d'Appui et de Coordination - 3 rue Edouard Belin",
		postalCode: "29200",
		city: "Brest",
		latitude: 48.417537,
		longitude: -4.460435,
		phone: "02 98 85 58 90",
		email: "contact@cra.bzh",
		website: "https://www.cra.bzh/",
		description: "Centre de Ressources Autisme de Bretagne.",
		metadata: { "pole-adulte": true },
	},
	{
		name: "CRA Champagne-Ardenne - Mission diagnostic et évaluation",
		address: "Clinique de Champagne - 1 rue de l’Université",
		postalCode: "51100",
		city: "Reims",
		latitude: 49.253206,
		longitude: 4.036421,
		phone: "03 26 78 39 67",
		email: "accueil@cra-champagne-ardenne.fr",
		website: "https://www.cra-champagne-ardenne.fr/",
		description: "Centre de Ressources Autisme de Grand Est.",
		metadata: { "pole-adulte": false },
	},
	{
		name: "CRA Corsica",
		address: "Immeuble Pingouin - Parc Azur - Bât C Av. Maréchal Juin",
		postalCode: "20000",
		city: "Ajaccio",
		latitude: 41.938421,
		longitude: 8.750711,
		phone: "04 95 50 50 40",
		email: "craajaccio@pep2b.corsica",
		website: "https://pep2b.corsica/cra-corsica/",
		description: "Centre de Ressources Autisme de Corse.",
		metadata: { "pole-adulte": true },
	},
	{
		name: "CRA Franche Comté",
		address: "3 rue Victor SELLIER",
		postalCode: "25000",
		city: "Besançon",
		latitude: 47.240278,
		longitude: 5.987853,
		phone: "03 81 21 82 44",
		email: "crafc@chu-besancon.fr",
		website: "https://www.cra-franchecomte.fr/",
		description: "Centre de Ressources Autisme de Bourgogne-Franche-Comté.",
		metadata: { "pole-adulte": false },
	},
	{
		name: "CRA Guadeloupe",
		address: "31 lotissement les Jardins de Moudong - 39 B Immeuble Névada",
		postalCode: "97122",
		city: "Baie-Mahault",
		latitude: 16.26119,
		longitude: -61.622748,
		phone: "05 90 25 23 90",
		description: "Centre de Ressources Autisme de Guadeloupe.",
		metadata: { "pole-adulte": true },
	},
	{
		name: "CRA Guyane",
		address:
			"10 rue des Galaxy - Bâtiment M - Structure du Centre Hospitalier de Cayenne",
		postalCode: "97300",
		city: "Cayenne",
		latitude: 4.923824,
		longitude: -52.313021,
		phone: "05 94 29 84 24",
		email: "cr.autisme@ch-cayenne.fr",
		website: "https://www.ght-guyane.fr/chc/enseignements/8",
		description: "Centre de Ressources Autisme de Guyane.",
		metadata: { "pole-adulte": false },
	},
	{
		name: "CRA Île-de-France",
		address: "10 rue Waldeck-Rochet - Bâtiment 521",
		postalCode: "93300",
		city: "Aubervilliers",
		latitude: 48.910874,
		longitude: 2.367652,
		phone: "01 49 28 54 20",
		email: "contact@craif.org",
		website: "https://craif.org/",
		description: "Centre de Ressources Autisme d'Île-de-France.",
		metadata: { "pole-adulte": true },
	},
	{
		name: "CRA Languedoc-Roussillon",
		address:
			"CHRU de Montpellier SMPEA Peyre Plantade - 291 avenue du Doyen Giraud",
		postalCode: "34295",
		city: "Montpellier",
		latitude: 43.633346,
		longitude: 3.850395,
		phone: "04 67 33 99 68",
		website: "https://www.autisme-ressources-lr.fr/",
		description: "Centre de Ressources Autisme d'Occitanie.",
		metadata: { "pole-adulte": false },
	},
	{
		name: "CRA Limousin",
		address: "Site de l’Hôpital du Cluzeau - 23 avenue Dominique Larrey",
		postalCode: "87042",
		city: "Limoges",
		latitude: 45.809995,
		longitude: 1.238592,
		phone: "05 55 05 89 84",
		email: "secretariat.cralimousin@chu-limoges.fr",
		website: "https://www.cralimousin.com/",
		description: "Centre de Ressources Autisme de Nouvelle-Aquitaine.",
		metadata: { "pole-adulte": true },
	},
	{
		name: "CRA Lorraine",
		address:
			"Centre Psychothérapique de Nancy - 1 rue du Docteur Archambault BP 11010",
		postalCode: "54521",
		city: "Laxou",
		latitude: 48.677975,
		longitude: 6.137205,
		phone: "03 83 92 66 76",
		email: "secretariat.ressourcesautisme@cpn-laxou.com",
		website:
			"https://epsytera.fr/cpn/centre-ressources-autisme-de-lorraine-cra/",
		description: "Centre de Ressources Autisme de Grand Est.",
		metadata: { "pole-adulte": false },
	},
	{
		name: "CRA Martinique",
		address:
			"Centre Hospitalier Maurice Despinoy (CHMD) Pôle Intersectoriel - Immeuble ANTARES-PFL Quartier Mangot Vulcin",
		postalCode: "97232",
		city: "Le Lamentin",
		latitude: 14.627957,
		longitude: -60.990444,
		phone: "00 596 596 48 83 60",
		email: "cra-martinique@ch-despinoy.fr",
		website: "https://www.ch-despinoy.fr/",
		description: "Centre de Ressources Autisme de Martinique.",
		metadata: { "pole-adulte": true },
	},
	{
		name: "CRA Mayotte",
		address: "6 rue Jardin Fleuri",
		postalCode: "97600",
		city: "Mamoudzou",
		latitude: -12.781756,
		longitude: 45.219735,
		phone: "02 69 61 64 00",
		description: "Centre de Ressources Autisme de Mayotte.",
		metadata: { "pole-adulte": false },
	},
	{
		name: "CRA Midi-Pyrénées",
		address: "2 Rue du Lieutenant Guy Dedieu - ZAC de la Cartoucherie",
		postalCode: "31300",
		city: "Toulouse",
		latitude: 43.601486,
		longitude: 1.40497,
		phone: "05 23 61 04 00",
		email: "accueil@cra-mp.info",
		website: "https://www.cra-mp.info/fr/",
		description: "Centre de Ressources Autisme d'Occitanie.",
		metadata: { "pole-adulte": true },
	},
	{
		name: "CRA Nord-Pas-De-Calais",
		address: "255 rue Nelson Mandela",
		postalCode: "59120",
		city: "Loos",
		latitude: 50.602192,
		longitude: 3.042332,
		phone: "03 20 60 62 59",
		email: "cra@cra-npdc.fr",
		website: "https://cra-npdc.fr/",
		description: "Centre de Ressources Autisme de Hauts-de-France.",
		metadata: { "pole-adulte": false },
	},
	{
		name: "CRA Normandie COM",
		address: "27 rue des Compagnons - CS 30001",
		postalCode: "14033",
		city: "Caen",
		latitude: 49.204399,
		longitude: -0.387612,
		phone: "02 31 06 58 20",
		email: "cra-sec@chu-caen.fr",
		website: "https://cra-normandie-com.fr/",
		description: "Centre de Ressources Autisme de Normandie.",
		metadata: { "pole-adulte": true },
	},
	{
		name: "CRA Normandie Seine Eure",
		address: "CH du Rouvray - 4 rue Paul Eluard BP 45",
		postalCode: "76301",
		city: "Sotteville-lès-Rouen",
		latitude: 49.399259,
		longitude: 1.099588,
		phone: "02 32 95 18 64",
		email: "cra@ch-lerouvray.fr",
		website: "http://cra-normandie-seine-eure.fr/",
		description: "Centre de Ressources Autisme de Normandie.",
		metadata: { "pole-adulte": false },
	},
	{
		name: "CRA Pays de la Loire",
		address: "Pôle Régional CHU Angers - 4 rue Larrey",
		postalCode: "49933",
		city: "Angers",
		latitude: 47.480948,
		longitude: -0.554426,
		phone: "02 41 35 31 21",
		email: "contact@cra-paysdelaloire.fr",
		website: "https://cra-paysdelaloire.fr/",
		description: "Centre de Ressources Autisme de Pays de la Loire.",
		metadata: { "pole-adulte": true },
	},
	{
		name: "CRA Picardie",
		address:
			"CHU Amiens-Picardie - Site Sud – Bât. St Vincent de Paul - 1 Rond-point du Pr Christian Cabrol",
		postalCode: "80054",
		city: "Amiens",
		latitude: 49.876182,
		longitude: 2.255731,
		phone: "03 22 66 75 40",
		email: "CRAdePicardie@chu-amiens.fr",
		website:
			"https://www.chu-amiens.fr/patients-et-visiteurs/services-et-contacts/les-structures-basees-en-ville/le-centre-ressources-autisme-picardie-cra-amiens-picardie/",
		description: "Centre de Ressources Autisme de Hauts-de-France.",
		metadata: { "pole-adulte": false },
	},
	{
		name: "CRA Poitou-Charentes",
		address: "CH Henri Laborit - 370 avenue Jacques Cœur CS 10587",
		postalCode: "86021",
		city: "Poitiers",
		latitude: 46.555504,
		longitude: 0.393951,
		phone: "05 49 44 57 59",
		email: "secretariat-cra@ch-poitiers.fr",
		website: "https://www.cra-pc.fr/",
		description: "Centre de Ressources Autisme de Nouvelle-Aquitaine.",
		metadata: { "pole-adulte": true },
	},
	{
		name: "CRA Provence-Alpes-Côte d'Azur - Pôle Marseille",
		address:
			"Hôpital Sainte-Marguerite - Service Universitaire de Psychiatrie de l’Enfant et de l’Adolescent du Pr. Poinso - 270 boulevard Sainte-Marguerite",
		postalCode: "13009",
		city: "Marseille",
		latitude: 43.262521,
		longitude: 5.412686,
		phone: "04 91 74 54 39",
		email: "secretariatcrapacaenfants-adolescents@ap-hm.fr",
		website: "https://cra-paca.centredoc.fr/",
		description: "Centre de Ressources Autisme de Provence-Alpes-Côte d’Azur.",
		metadata: { "pole-adulte": false },
	},
	{
		name: "CRA Réunion",
		address: "14 ruelle Rivière",
		postalCode: "97436",
		city: "Saint-Leu La Réunion",
		latitude: -21.169438,
		longitude: 55.289241,
		phone: "02 62 22 59 52",
		email: "secretaire.cra@clairejoie.re",
		website: "https://www.cria.re/index.php",
		description: "Centre de Ressources Autisme de La Réunion.",
		metadata: { "pole-adulte": true },
	},
	{
		name: "CRA Rhône-Alpes",
		address:
			"Centre Hospitalier le Vinatier Bât. 211 - 95 boulevard Pinel BP 30039",
		postalCode: "69678",
		city: "Bron",
		latitude: 45.742052,
		longitude: 4.894137,
		phone: "04 37 91 54 65",
		website: "https://www.cra-rhone-alpes.org/",
		description: "Centre de Ressources Autisme d'Auvergne-Rhône-Alpes.",
		metadata: { "pole-adulte": false },
	},
];

// ─── Marqueurs MDPH ───────────────────────────────────────────────────────────

const mdphMarkers: MarkerInput[] = [
	{
		name: "Maison de l'Autonomie (MDA) - Alpes-Maritimes",
		address: "BP 3007, Département des Alpes-Maritimes Maison de l'Autonomie",
		postalCode: "06201",
		city: "Nice",
		latitude: 43.71273,
		longitude: 7.25092,
		phone: "08 05 56 60 06",
		website: "https://mda.departement06.fr/",
	},
	{
		name: "Maison Départemental de l'Autonomie de l'Oise (MDA) - Oise",
		address: "CS 80941, Conseil Départemental de l'Oise 1 rue Cambry",
		postalCode: "60006",
		city: "Beauvais",
		latitude: 49.439313,
		longitude: 2.087881,
		phone: "08 00 89 44 21",
		email: "allo-oise-handicap@oise.fr",
		website: "https://mda.oise.fr",
	},
	{
		name: "Maison départementale de l'autonomie (MDA) - Isère",
		address: "15 avenue Doyen-Louis-Weil",
		postalCode: "38000",
		city: "Grenoble",
		latitude: 45.192283,
		longitude: 5.7123,
		phone: "04 38 12 48 48",
		email: "mda38@isere.fr",
		website: "https://www.isere.fr/mda38",
	},
	{
		name: "Maison départementale de l'autonomie (MDA-MDPH) - Saône-et-Loire",
		address: "18 rue de Flacé Espace Duhesme",
		postalCode: "71026",
		city: "Mâcon",
		latitude: 46.325859,
		longitude: 4.810979,
		phone: "03 85 21 51 30",
		email: "mdph@saoneetloire71.fr",
		website: "https://www.saoneetloire71.fr",
	},
	{
		name: "Maison départementale-métropolitaine des personnes handicapées (MDMPH) - Rhône-Lyon",
		address: "CS 33569, Métropole de Lyon 20 rue du Lac",
		postalCode: "69505",
		city: "Lyon",
		latitude: 45.758,
		longitude: 4.835,
		phone: "04 26 83 86 86",
		email: "handicap@grandlyon.com",
		website: "https://www.grandlyon.com",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Ain",
		address: "BP 50415, 13 avenue de la Victoire",
		postalCode: "01012",
		city: "Bourg-en-Bresse",
		latitude: 46.20244,
		longitude: 5.217513,
		phone: "3001",
		email: "mdph@ain.fr",
		website: "https://www.ain.fr/solutions/mdph-ain/",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Aisne",
		address: "28 rue Fernand-Christ",
		postalCode: "02000",
		city: "Laon",
		latitude: 49.571511,
		longitude: 3.603014,
		phone: "03 23 24 89 89",
		email: "mdph@aisne.fr",
		website:
			"https://www.aisne.com/a-votre-service/personnes-en-situation-de-handicap",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Allier",
		address: "Château de Bellevue Rue Aristide-Briand",
		postalCode: "03400",
		city: "Yzeure",
		latitude: 46.561081,
		longitude: 3.343622,
		phone: "04 70 34 15 70",
		email: "autonomie-tsdmoulins@allier.fr",
		website: "http://www.allier.fr/",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Alpes-de-Haute-Provence",
		address: "4 rue de la Grave Immeuble François-Cuzin",
		postalCode: "04000",
		city: "Digne-les-Bains",
		latitude: 44.089893,
		longitude: 6.232618,
		phone: "04 92 30 09 90",
		email: "contact@mdph04.fr",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Ardennes",
		address: "55 avenue Charles-de-Gaulle",
		postalCode: "08000",
		city: "Charleville-Mézières",
		latitude: 49.768162,
		longitude: 4.715689,
		phone: "03 24 41 39 50",
		email: "courrier@mdph08.fr",
		website: "https://www.mdph08.fr",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Ardèche",
		address: "Pôle Astier Froment",
		postalCode: "07006",
		city: "Privas",
		latitude: 44.726042,
		longitude: 4.594919,
		phone: "08 00 07 07 00",
		email: "mdph@ardeche.fr",
		website:
			"https://www.ardeche.fr/114-maison-departementale-des-personnes-handicapees.htm",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Ariège",
		address: "5-7 rue du Cap-de-la-Ville",
		postalCode: "09000",
		city: "Foix",
		latitude: 42.962777,
		longitude: 1.6005,
		phone: "05 61 02 08 04",
		email: "mdpsh@ariege.fr",
		website:
			"https://ariege.fr/nos-actions/solidarites/handicap/la-maison-departementale-des-personnes-en-situation-de-handicap-mdpsh/",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Aube",
		address: "Cité administrative des Vassaules",
		postalCode: "10026",
		city: "Troyes",
		latitude: 48.292817,
		longitude: 4.075149,
		phone: "03 25 42 65 70",
		email: "mdph@aube.fr",
		website: "http://www.mdph10.fr",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Aude",
		address: "18 rue du Moulin-de-la-Seigne",
		postalCode: "11855",
		city: "Carcassonne",
		latitude: 43.228208,
		longitude: 2.350944,
		phone: "08 00 77 77 32",
		email: "mdph@aude.fr",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Aveyron",
		address: "8 rue François-Mazenq",
		postalCode: "12000",
		city: "Rodez",
		latitude: 44.350377,
		longitude: 2.568368,
		phone: "05 65 73 32 60",
		email: "accueil@mdph12.fr",
		website: "https://www.mdph12.fr/fr",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Bas-Rhin",
		address: "6 A rue du Verdon",
		postalCode: "67100",
		city: "Strasbourg",
		latitude: 48.551037,
		longitude: 7.737285,
		phone: "03 69 49 39 00",
		email: "Accueil.mdph@alsace.eu",
		website: "https://www.alsace.eu",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Bouches-du-Rhône",
		address: "CS 80096, 4 quai d'Arenc",
		postalCode: "13304",
		city: "Marseille",
		latitude: 43.282,
		longitude: 5.405,
		phone: "08 00 81 48 44",
		email: "accueil.information.mdph@mdph13.fr",
		website: "https://www.mdph13.fr",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Calvados",
		address: "17 avenue Pierre-Mendès-France",
		postalCode: "14000",
		city: "Caen",
		latitude: 49.177688,
		longitude: -0.349066,
		phone: "08 00 10 05 22",
		email: "mdph@calvados.fr",
		website: "https://www.calvados.fr/accueil.html",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Cantal",
		address:
			"Pôle solidarité départementale 3 rue Alexandre Pinard Espace Georges-Pompidou",
		postalCode: "15000",
		city: "Aurillac",
		latitude: 44.918771,
		longitude: 2.435053,
		phone: "04 71 43 88 88",
		email: "accueilmda@cantal.fr",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Charente",
		address: "15 boulevard Jean Moulin",
		postalCode: "16000",
		city: "Angoulême",
		latitude: 45.630773,
		longitude: 0.146341,
		phone: "08 00 00 16 00",
		website: "https://www.mdph-16.fr",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Charente-Maritime",
		address: "61 rue de Jéricho",
		postalCode: "17000",
		city: "La Rochelle",
		latitude: 46.166398,
		longitude: -1.16162,
		phone: "08 00 15 22 15",
		email: "mdph@charente-maritime.fr",
		website:
			"https://la.charente-maritime.fr/personnes-handicapees/maison-departementale-des-personnes-handicapees",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Cher",
		address: "Pyramides du conseil départemental 7 route de Guerry",
		postalCode: "18000",
		city: "Bourges",
		latitude: 47.082882,
		longitude: 2.402294,
		phone: "02 48 27 31 31",
		email: "autonomie.mdph@departement18.fr",
		website: "https://www.departement18.fr/-Personnes-handicapees-",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Corrèze",
		address: "ZI Espace Cueille 2 rue du Docteur-Ramon",
		postalCode: "19000",
		city: "Tulle",
		latitude: 45.254859,
		longitude: 1.759193,
		phone: "05 19 07 85 00",
		email: "autonomie@correze.fr",
		website:
			"https://www.correze.fr/nos-missions/seniors-handicap/handicap/sinformer-et-etre-accompagne-pour-les-personnes-en-situation-de-handicap",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Corse-du-Sud",
		address: "Quartier St Joseph Avenue du Mont Thabor Immeuble Castellani",
		postalCode: "20700",
		city: "Ajaccio",
		latitude: 41.93368,
		longitude: 8.715325,
		phone: "04 95 10 40 90",
		email: "corsedusud@mdph.corsica",
		website: "https://dossier-mdph.com/2a-corse-du-sud/",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Creuse",
		address: "BP 59, 2 bis avenue de la République",
		postalCode: "23011",
		city: "Guéret",
		latitude: 46.170945,
		longitude: 1.871685,
		phone: "05 44 30 28 28",
		email: "mdph23@creuse.fr",
		website: "https://mdphenligne.cnsa.fr/mdph/23",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Côte-d'Or",
		address: "1 rue Joseph Tissot",
		postalCode: "21035",
		city: "Dijon",
		latitude: 47.32658,
		longitude: 5.04227,
		phone: "03 80 63 31 60",
		email: "mdph@cotedor.fr",
		website:
			"https://www.cotedor.fr/votre-service/personnes-en-situation-de-handicap",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Côtes-d'Armor",
		address: "3 rue Villiers-de-l'Isle-Adam",
		postalCode: "22190",
		city: "Plérin",
		latitude: 48.529074,
		longitude: -2.765537,
		phone: "02 96 01 01 80",
		email: "mdph@mdph.cotesdarmor.fr",
		website: "http://mdph.cotesdarmor.fr",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Deux-Sèvres",
		address: "68 rue Alsace-Lorraine",
		postalCode: "79000",
		city: "Niort",
		latitude: 46.328501,
		longitude: -0.457924,
		phone: "05 49 06 63 63",
		email: "autonomie-niortais@deux-sevres.fr",
		website:
			"https://www.deux-sevres.fr/nos-missions/les-personnes-handicapees/la-maison-departementale-des-personnes-handicapees-mdph79",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Dordogne",
		address:
			"Bâtiment E Rue du 26e Régiment d'Infanterie Cité administrative Bugeaud",
		postalCode: "24016",
		city: "Périgueux",
		latitude: 45.193072,
		longitude: 0.711299,
		phone: "05 53 02 03 55",
		email: "mdph24@dordogne.fr",
		website: "https://mdph.dordogne.fr/",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Doubs",
		address: "13-15 rue de la Préfecture",
		postalCode: "25043",
		city: "Besançon",
		latitude: 47.234659,
		longitude: 6.024483,
		phone: "03 81 25 90 00",
		email: "contact@mdph.doubs.fr",
		website: "https://mdph.doubs.fr/",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Drôme",
		address: "Bâtiment G Parc de Lautagne 42 C avenue des Langories",
		postalCode: "26905",
		city: "Valence",
		latitude: 44.920925,
		longitude: 4.92297,
		phone: "04 75 79 70 09",
		email: "dromesolidarites@ladrome.fr",
		website:
			"https://www.ladrome.fr/mon-quotidien/solidarites/la-maison-departementale-de-lautonomie/",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Essonne",
		address: "93 rue Henri Rochefort",
		postalCode: "91000",
		city: "Évry",
		latitude: 48.624341,
		longitude: 2.436396,
		phone: "01 60 76 11 00",
		email: "mdphe@cd-essonne.fr",
		website: "https://www.essonne.fr/sante-social-solidarite/handicap/la-mdph",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Eure",
		address: "11 rue Jean-de-la-Bruyère",
		postalCode: "27032",
		city: "Évreux",
		latitude: 49.004958,
		longitude: 1.156336,
		phone: "02 32 31 96 13",
		email: "mdph-eure@eure.fr",
		website: "https://www.mdph27.fr",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Eure-et-Loir",
		address: "57 bis rue du Docteur-Maunoury",
		postalCode: "28000",
		city: "Chartres",
		latitude: 48.439721,
		longitude: 1.482244,
		phone: "02 37 33 46 46",
		email: "contact@mda28.fr",
		website: "https://www.eurelien.fr/guide/autonomie",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Finistère",
		address: "CS 52019, 1 C rue Félix-le-Dantec",
		postalCode: "29018",
		city: "Quimper",
		latitude: 47.978772,
		longitude: -4.103834,
		phone: "02 98 90 50 50",
		email: "contact@mdph29.fr",
		website: "https://www.mdph29.fr/",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Gard",
		address: "176 Boulevard du Président-Salvador-Allende",
		postalCode: "30000",
		city: "Nîmes",
		latitude: 43.823416,
		longitude: 4.36861,
		phone: "08 00 20 55 88",
		email: "mdph@gard.fr",
		website: "https://www.gard.fr/",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Gers",
		address: "17 Rue Lafayette",
		postalCode: "32000",
		city: "Auch",
		latitude: 43.656961,
		longitude: 0.57082,
		phone: "05 62 61 76 76",
		email: "mdph32@mdph32.fr",
		website: "http://www.mdph32.fr",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Gironde",
		address: "CS 51914, MDPH 33 Esplanade Charles de Gaulle",
		postalCode: "33074",
		city: "Bordeaux",
		latitude: 44.837353,
		longitude: -0.584767,
		phone: "05 56 99 66 99",
		email: "accueil-autonomie@gironde.fr",
		website: "http://www.mdph33.fr",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Guadeloupe",
		address: "Pôle médico-social Conseil départemental Rue du Docteur Hélène",
		postalCode: "97190",
		city: "Le Gosier",
		latitude: 16.229731,
		longitude: -61.472339,
		phone: "05 90 83 14 28",
		email: "contact@mdph-971.fr",
		website: "https://www.cg971.fr/",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Guyane",
		address:
			"Novaparc 7 Angle avenue Mère-Teresa et avenue Vendome Rue des Galaxies",
		postalCode: "97300",
		city: "Cayenne",
		latitude: 4.925248,
		longitude: -52.311583,
		phone: "05 94 39 16 80",
		email: "mdph-guyane@mdph973.fr",
		website: "https://www.mdph973.fr",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Haute-Corse",
		address:
			"Maison départementale des personnes handicapées Rond-point du Maréchal-Leclerc",
		postalCode: "20405",
		city: "Bastia",
		latitude: 42.687608,
		longitude: 9.435179,
		phone: "04 95 30 08 35",
		website: "https://dossier-mdph.com/bastia/",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Haute-Garonne",
		address: "CS 87089, 10 place Alphonse-Jourdain",
		postalCode: "31070",
		city: "Toulouse",
		latitude: 43.61117,
		longitude: 1.42969,
		phone: "08 00 31 01 31",
		email: "mdph@cd31.fr",
		website: "https://www.mdph31.fr/",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Haute-Loire",
		address: "Maison Départementale de l'Autonomie 78 bis avenue Maréchal-Foch",
		postalCode: "43000",
		city: "Puy-en-Velay",
		latitude: 45.034919,
		longitude: 3.886909,
		phone: "04 71 07 21 80",
		email: "accueil.mda@hauteloire.fr",
		website: "https://www.hauteloire.fr/La-Maison-Departementale-des.html",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Haute-Marne",
		address: "4 cours Marcel-Baron",
		postalCode: "52901",
		city: "Chaumont",
		latitude: 48.114296,
		longitude: 5.141597,
		phone: "03 25 01 19 51",
		email: "mdph@haute-marne.fr",
		website: "https://mdphenligne.cnsa.fr/mdph/52",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Hautes-Alpes",
		address: "29 bis avenue Commandant-Dumont",
		postalCode: "05000",
		city: "Gap",
		latitude: 44.564962,
		longitude: 6.083633,
		phone: "04 86 15 31 50",
		email: "mda@hautes-alpes.fr",
		website: "https://mda.hautes-alpes.fr/",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Haute-Savoie",
		address: "26 avenue de Chevêne",
		postalCode: "74003",
		city: "Annecy",
		latitude: 45.900859,
		longitude: 6.116429,
		phone: "04 50 33 22 50",
		email: "mdph@mdph74.fr",
		website: "http://www.mdph74.fr",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Haute-Saône",
		address: "1 rue Jean-Bernard-Derosne",
		postalCode: "70000",
		city: "Vesoul",
		latitude: 47.620888,
		longitude: 6.149869,
		phone: "03 84 96 12 80",
		email: "mdph@haute-saone.fr",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Hautes-Pyrénées",
		address: "Place Ferré",
		postalCode: "65000",
		city: "Tarbes",
		latitude: 43.228199,
		longitude: 0.075349,
		phone: "05 62 56 73 50",
		email: "mdph65@ha-py.fr",
		website: "https://www.mdph65.fr/",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Haute-Vienne",
		address: "BP 73129, 8 place des Carmes",
		postalCode: "87031",
		city: "Limoges",
		latitude: 45.830293,
		longitude: 1.249702,
		phone: "05 55 14 14 50",
		email: "contact.mdph@haute-vienne.fr",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Haut-Rhin",
		address: "100, avenue d'Alsace",
		postalCode: "68006",
		city: "Colmar",
		latitude: 48.070791,
		longitude: 7.364962,
		phone: "03 89 30 68 10",
		email: "mdph@haut-rhin.fr",
		website: "https://www.alsace.eu/",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Hauts-de-Seine",
		address: "Esplanade Mona-Lisa 12 avenue Léonard-de-Vinci",
		postalCode: "92400",
		city: "Courbevoie",
		latitude: 48.896538,
		longitude: 2.236587,
		phone: "01 41 91 92 50",
		website: "https://mdphenligne.cnsa.fr/",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Hérault",
		address: "1350 rue d'Alco",
		postalCode: "34086",
		city: "Montpellier",
		latitude: 43.617368,
		longitude: 3.839961,
		phone: "04 67 67 69 30",
		website: "http://www.mdph34.fr",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Ille-et-Vilaine",
		address: "13 avenue de Cucillé",
		postalCode: "35030",
		city: "Rennes",
		latitude: 48.126017,
		longitude: -1.698249,
		phone: "08 00 35 35 05",
		email: "contact@mdph35.fr",
		website: "http://www.mdph35.fr",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Indre",
		address: "4 rue Eugène-Rolland Centre Colbert",
		postalCode: "36000",
		city: "Châteauroux",
		latitude: 46.810549,
		longitude: 1.703886,
		phone: "02 54 35 24 24",
		email: "mdph36@mdph36.fr",
		website: "http://www.mdph36.fr",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Indre-et-Loire",
		address: "38 rue Édouard-Vaillant",
		postalCode: "37040",
		city: "Tours",
		latitude: 47.388341,
		longitude: 0.697168,
		phone: "02 47 75 26 66",
		email: "info@mdph37.fr",
		website: "http://www.mdph37.fr",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Jura",
		address: "BP 40044, 355 boulevard Jules-Ferry",
		postalCode: "39002",
		city: "Lons-le-Saunier",
		latitude: 46.671589,
		longitude: 5.543854,
		phone: "03 84 87 40 44",
		email: "mdph39@jura.fr",
		website: "https://www.mdph39.fr/",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Landes",
		address: "836 avenue Éloi-Ducom",
		postalCode: "40025",
		city: "Mont-de-Marsan",
		latitude: 43.8909,
		longitude: -0.486424,
		phone: "05 58 51 53 73",
		email: "mlph@landes.fr",
		website: "https://www.handicaplandes.fr/",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Loire",
		address: "Hôtel du département 2 rue Charles-de-Gaulle",
		postalCode: "42022",
		city: "Saint-Étienne",
		latitude: 45.442185,
		longitude: 4.386432,
		phone: "04 77 49 91 91",
		email: "accueil@mla.loire.fr",
		website: "https://www.mdphloire.fr/jcms/lw_1421607/fr/accueil",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Loire-Atlantique",
		address: "CS 70128, 1 avenue Jacques-Cartier",
		postalCode: "44802",
		city: "Saint-Herblain",
		latitude: 47.222839,
		longitude: -1.634067,
		phone: "02 28 09 40 50",
		email: "accueil.mdph@loire-atlantique.fr",
		website: "https://www.loire-atlantique.fr",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Loiret",
		address:
			"Maison départementale de l'autonomie 3 bis avenue des Droits-de-l'Homme",
		postalCode: "45000",
		city: "Orléans",
		latitude: 47.873569,
		longitude: 1.911358,
		phone: "02 38 25 45 45",
		email: "mda.contact@loiret.fr",
		website: "https://mdphenligne.cnsa.fr/mdph/45",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Loir-et-Cher",
		address: "Cité administrative porte D 34 avenue Maunoury",
		postalCode: "41000",
		city: "Blois",
		latitude: 47.581228,
		longitude: 1.316533,
		phone: "02 54 58 44 40",
		email: "accueil.mdph@departement41.fr",
		website:
			"https://www.departement41.fr/services-en-ligne/etre-accompagne/vivre-autonome-41-personnes-agees-handicapees/la-mdph/",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Lot",
		address: "304 rue Victor-Hugo",
		postalCode: "46000",
		city: "Cahors",
		latitude: 44.443319,
		longitude: 1.438009,
		phone: "05 65 53 51 40",
		email: "mdph@mdph46.fr",
		website: "https://lot.fr/maison-des-personnes-handicapees",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Lot-et-Garonne",
		address: "1633 avenue du Maréchal-Leclerc",
		postalCode: "47000",
		city: "Agen",
		latitude: 44.19213,
		longitude: 0.613931,
		phone: "05 53 69 20 50",
		email: "contact@mdph47.fr",
		website: "https://www.mdph47.fr",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Lozère",
		address: "6 avenue du Père-Coudrin",
		postalCode: "48000",
		city: "Mende",
		latitude: 44.517503,
		longitude: 3.504122,
		phone: "04 66 49 60 70",
		email: "accueilmdph48@mdph48.fr",
		website: "http://lozere.fr/la-mdph.html",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Maine-et-Loire",
		address: "CS 94104, Maison départementale de l'autonomie",
		postalCode: "49941",
		city: "Angers",
		latitude: 47.467471,
		longitude: -0.561615,
		phone: "02 41 81 60 77",
		email: "contact@mda.maine-et-loire.fr",
		website: "http://www.mda.maine-et-loire.fr",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Manche",
		address: "Maison départementale de l'autonomie 98 route de candol",
		postalCode: "50050",
		city: "Saint-Lô",
		latitude: 49.113843,
		longitude: -1.080182,
		phone: "02 33 05 55 50",
		website: "https://www.manche.fr/",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Marne",
		address:
			"MDPH de la Marne Centre d'affaires Patton 50 avenue du Général-Patton",
		postalCode: "51000",
		city: "Châlons-en-Champagne",
		latitude: 48.955254,
		longitude: 4.368278,
		phone: "03 26 26 06 06",
		email: "accueil@mdph51.fr",
		website: "https://www.mdph51.fr/",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Martinique",
		address: "Espace Pythagore 1 Impasse Paulette-Pigeon",
		postalCode: "97200",
		city: "Fort-de-France",
		latitude: 14.636435,
		longitude: -61.064096,
		phone: "05 96 70 09 95",
		email: "contact@mdph972.fr",
		website: "https://www.mmph.fr/",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Mayenne",
		address: "12 quai de Bootz Centre Jean-Monnet",
		postalCode: "53014",
		city: "Laval",
		latitude: 48.059596,
		longitude: -0.77159,
		phone: "02 43 67 75 77",
		email: "mda@lamayenne.fr",
		website: "http://www.lamayenne.fr",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Meurthe-et-Moselle",
		address: "CS 31030, 123 rue Ernest-Albert",
		postalCode: "54521",
		city: "Laxou",
		latitude: 48.687252,
		longitude: 6.155848,
		phone: "03 83 97 44 20",
		email: "mdphaccueil@mdph.departement54.fr",
		website: "https://mdph.meurthe-et-moselle.fr/",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Meuse",
		address: "5 espace Theuriet",
		postalCode: "55000",
		city: "Bar-le-Duc",
		latitude: 48.773898,
		longitude: 5.164877,
		phone: "03 29 46 70 70",
		email: "contact@mdph55.fr",
		website:
			"https://www.meuse.fr/proche/en-situation-de-handicap/maison-departementale-des-personnes-handicapees/la-maison-departementale-des-personnes-handicapees-de-la-meuse",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Morbihan",
		address: "Parc d'activités de Laroiseau 16 rue Ella-Maillart",
		postalCode: "56000",
		city: "Vannes",
		latitude: 47.659971,
		longitude: -2.752192,
		phone: "02 97 62 74 74",
		email: "contact@mda56.fr",
		website:
			"https://www.morbihan.fr/nos-actions/accompagnement-tout-au-long-de-la-vie/handicap/de-laide-pour-vos-demarches/la-maison-departementale-de-lautonomie-mda",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Moselle",
		address: "Bâtiment D Entrée D3 1 rue Claude Chappe",
		postalCode: "57076",
		city: "Metz",
		latitude: 49.108385,
		longitude: 6.194891,
		phone: "03 87 21 83 00",
		email: "mdph@moselle.fr",
		website: "http://www.mdph57.fr/",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Nièvre",
		address: "11 bis rue Émile-Combes",
		postalCode: "58000",
		city: "Nevers",
		latitude: 47.002821,
		longitude: 3.159235,
		phone: "03 86 71 05 50",
		email: "mdph@nievre.fr",
		website: "https://mdphenligne.cnsa.fr",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Nord - Site de Dunkerque",
		address: "CS 82510, 51 rue Gustave-Delory",
		postalCode: "59040",
		city: "Lille",
		latitude: 50.633633,
		longitude: 3.072709,
		email: "mdph@lenord.fr",
		website: "https://mdph.lenord.fr/",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Nord - Site de Lille",
		address: "CS 82510, 51 rue Gustave-Delory",
		postalCode: "59040",
		city: "Lille",
		latitude: 50.633633,
		longitude: 3.072709,
		email: "mdph@lenord.fr",
		website: "https://mdph.lenord.fr/",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Nord - Site de Valenciennes",
		address: "CS 82510, 51 rue Gustave-Delory",
		postalCode: "59040",
		city: "Lille",
		latitude: 50.633633,
		longitude: 3.072709,
		email: "mdph@lenord.fr",
		website: "https://mdph.lenord.fr/",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Nord - Siège de Lille",
		address: "CS 82510, 51 rue Gustave-Delory",
		postalCode: "59040",
		city: "Lille",
		latitude: 50.633633,
		longitude: 3.072709,
		phone: "03 59 73 73 73",
		email: "mdph@lenord.fr",
		website: "https://mdph.lenord.fr/",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Orne",
		address: "13 rue Marchand-Saillant",
		postalCode: "61005",
		city: "Alençon",
		latitude: 48.434745,
		longitude: 0.111465,
		phone: "02 33 15 00 31",
		email: "mda.ph@orne.fr",
		website: "http://www.mdph61.fr",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Paris",
		address: "69 rue de la Victoire",
		postalCode: "75009",
		city: "Paris",
		latitude: 48.875181,
		longitude: 2.333373,
		phone: "01 53 32 39 39",
		email: "contact@mdph.paris.fr",
		website: "https://handicap.paris.fr",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Pas-de-Calais",
		address: "BP 90266, 9 rue Willy-Brandt Parc d'activités des Bonnettes",
		postalCode: "62005",
		city: "Arras",
		latitude: 50.287896,
		longitude: 2.768267,
		phone: "03 21 21 84 00",
		website: "https://www.mdph62.fr/ma-mdph",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Puy-de-Dôme",
		address: "11 rue Vaucanson",
		postalCode: "63100",
		city: "Clermont-Ferrand",
		latitude: 45.786758,
		longitude: 3.107662,
		phone: "04 73 74 51 20",
		email: "mdph@mdph63.fr",
		website: "https://mdph.puy-de-dome.fr/accueil.html",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Pyrénées-Atlantiques",
		address: "Rue Pierre Bonnard Cité administrative",
		postalCode: "64000",
		city: "Pau",
		latitude: 43.31002,
		longitude: -0.3613,
		phone: "05 59 04 64 64",
		email: "mda@le64.fr",
		website: "https://www.mda64.fr",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Pyrénées-Orientales",
		address: "30 rue Pierre-Bretonneau",
		postalCode: "66100",
		city: "Perpignan",
		latitude: 42.667642,
		longitude: 2.886833,
		phone: "04 68 39 99 00",
		email: "mdph66@cd66.fr",
		website:
			"https://www.ledepartement66.fr/service/la-mdph-66-maison-departementale-des-personnes-handicapees/",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - La Réunion",
		address: "BP 60183, 13 rue Fénelon",
		postalCode: "97464",
		city: "Saint-Denis",
		latitude: -20.884797,
		longitude: 55.449211,
		phone: "08 00 00 02 62",
		email: "mdph974@mdph.re",
		website: "https://www.mdph.re/",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Savoie",
		address: "110 rue Sainte Rose",
		postalCode: "73000",
		city: "Chambéry",
		latitude: 45.56599,
		longitude: 5.93564,
		phone: "04 79 75 39 60",
		email: "mdph@mdph73.fr",
		website: "https://www.savoie.fr/",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Seine-et-Marne",
		address: "16 rue de l'Aluminium",
		postalCode: "77543",
		city: "Savigny-le-Temple",
		latitude: 48.594588,
		longitude: 2.587496,
		phone: "01 64 19 11 40",
		website: "https://mdph77.fr/fr",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Seine-Maritime",
		address: "13 rue Poret de Blosseville",
		postalCode: "76100",
		city: "Rouen",
		latitude: 49.437177,
		longitude: 1.082457,
		phone: "02 32 18 86 87",
		email: "mdph@seinemaritime.fr",
		website:
			"https://www.seinemaritime.fr/nos-actions/action-sociale/handicap/",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Seine-Saint-Denis",
		address: "Immeuble Pulse 44 rue Proudhon",
		postalCode: "93210",
		city: "Saint-Denis",
		latitude: 48.906345,
		longitude: 2.365183,
		phone: "01 43 93 86 86",
		email: "mdaa@seinesaintdenis.fr",
		website: "https://place-handicap.fr/",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Somme",
		address: "Site Simone VEIL 49 Boulevard de Châteaudun",
		postalCode: "80000",
		city: "Amiens",
		latitude: 49.882572,
		longitude: 2.283349,
		phone: "03 22 97 24 10",
		email: "mdph@somme.fr",
		website: "https://mdph.somme.fr",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Tarn",
		address: "BP 10055, 10 rue des 3 Tarn",
		postalCode: "81027",
		city: "Albi",
		latitude: 43.930374,
		longitude: 2.136314,
		phone: "05 81 27 70 07",
		email: "contact.mda@tarn.fr",
		website: "https://mda.tarn.fr/accueil",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Tarn-et-Garonne",
		address: "28 rue de la Banque",
		postalCode: "82013",
		city: "Montauban",
		latitude: 44.013389,
		longitude: 1.35756,
		phone: "08 00 10 28 48",
		email: "mdph@ledepartement82.fr",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Territoire de Belfort",
		address: "Rue de l'As-de-Carreau",
		postalCode: "90008",
		city: "Belfort",
		latitude: 47.640938,
		longitude: 6.857469,
		phone: "03 70 04 89 89",
		email: "contact@mdph90.fr",
		website: "https://www.territoiredebelfort.fr",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Val-de-Marne",
		address: "7-9 voie Félix Éboué Immeuble Solidarité",
		postalCode: "94046",
		city: "Créteil",
		latitude: 48.784506,
		longitude: 2.452976,
		phone: "01 43 99 79 00",
		email: "mdph94@valdemarne.fr",
		website:
			"https://www.valdemarne.fr/a-votre-service/handicap/maison-departementale-des-personnes-handicapees-mdph",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Val-d'Oise",
		address: "Bâtiment H Conseil départemental du Val d'Oise",
		postalCode: "95032",
		city: "Cergy-Pontoise",
		latitude: 49.047592,
		longitude: 2.099968,
		email: "maisonduhandicap@valdoise.fr",
		website: "https://www.mdph.valdoise.fr/",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Var",
		address: "Point d 'accueil Centre de solidarité 380 rue Jean Aicard",
		postalCode: "83300",
		city: "Draguigan",
		latitude: 43.532153,
		longitude: 6.459174,
		phone: "04 94 85 00 14",
		website: "https://mdph.var.fr",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Vaucluse",
		address: "22 boulevard Saint-Michel",
		postalCode: "84096",
		city: "Avignon",
		latitude: 43.94303,
		longitude: 4.812154,
		phone: "08 00 80 05 79",
		email: "accueilmdph@mdph84.fr",
		website: "https://www.vaucluse.fr",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Vendée",
		address: "40 rue Foch",
		postalCode: "85923",
		city: "La Roche-sur-Yon",
		latitude: 46.674374,
		longitude: -1.428543,
		phone: "08 00 85 85 01",
		email: "mva@vendee.fr",
		website:
			"https://www.vendee.fr/Solidarite-et-education/Handicap/23398-La-MDPH-de-Vendee-a-votre-disposition/http-vendee.fr-MDPH",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Vienne",
		address: "39 rue de Beaulieu",
		postalCode: "86000",
		city: "Poitiers",
		latitude: 46.576402,
		longitude: 0.369153,
		phone: "05 49 45 97 77",
		email: "mdph-accueil@departement86.fr",
		website: "https://www.mdph86.fr/",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Vosges",
		address: "2 rue Grennevo",
		postalCode: "88026",
		city: "Épinal",
		latitude: 48.168735,
		longitude: 6.450857,
		phone: "03 29 29 09 91",
		email: "mdph88@vosges.fr",
		website: "https://www.vosges.fr/dispositifs/handicap",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Yonne",
		address: "CS 50316, 10 route de Saint-Georges",
		postalCode: "89005",
		city: "Perrigny",
		latitude: 47.810087,
		longitude: 3.535455,
		phone: "03 86 72 89 72",
		email: "mdphy@yonne.fr",
		website: "http://www.mdph89.fr",
	},
	{
		name: "Maison départementale des personnes handicapées (MDPH) - Yvelines",
		address: "TSA 60100",
		postalCode: "78539",
		city: "Buc",
		latitude: 48.772808,
		longitude: 2.118783,
		phone: "08 01 80 11 00",
		email: "autonomie78@yvelines.fr",
		website:
			"https://www.yvelines.fr/fiche/maison-departementale-des-personnes-handicapees-mdph-78/",
	},
	{
		name: "Sarthe Autonomie (Maison départementale de l'autonomie) - Sarthe",
		address: "11 rue du Pied Sec",
		postalCode: "72019",
		city: "Le Mans",
		latitude: 47.983301,
		longitude: 0.203765,
		phone: "08 00 52 62 72",
		email: "sartheautonomie@sarthe.fr",
	},
];

// ─── Carte ────────────────────────────────────────────────────────────────────

const mapData = {
	name: "Carte des structures",
	slug: "carte-des-structures",
	title: "Structures d'accompagnement en France",
	description:
		"Retrouvez les Centres de Ressources Autisme (CRA) et les Maisons Départementales des Personnes Handicapées (MDPH) sur le territoire français.",
	defaultLatitude: 46.6,
	defaultLongitude: 2.3,
	defaultZoom: 5,
	fitToMarkers: true,
};

// ─── Fonctions de création ────────────────────────────────────────────────────

async function createMapCategory(
	payload: Payload,
	data: (typeof mapCategories)[number],
): Promise<number> {
	try {
		const category = await payload.create({
			collection: "map-categories",
			data,
		});
		return category.id;
	} catch (error) {
		throw new Error(
			`Erreur lors de la création de la catégorie "${data.name}" : ${error}`,
		);
	}
}

async function createMapMarker(
	payload: Payload,
	data: MarkerInput,
	categoryId: number,
): Promise<void> {
	const { metadata, ...rest } = data;
	const hasCoords =
		typeof data.latitude === "number" && typeof data.longitude === "number";
	try {
		await payload.create({
			collection: "map-markers",
			data: {
				...rest,
				category: categoryId,
				...(metadata !== undefined ? { metadata } : {}),
			},
			context: hasCoords ? { skipGeocode: true } : {},
		});
	} catch (error) {
		throw new Error(
			`Erreur lors de la création du marqueur "${data.name}" : ${error}`,
		);
	}
}

async function createMap(
	payload: Payload,
	data: typeof mapData,
	categoryIds: number[],
	allowedCustomFieldFilters: Array<{ categoryId: number; key: string }>,
): Promise<void> {
	try {
		await payload.create({
			collection: "maps",
			data: {
				...data,
				categories: categoryIds,
				allowedCustomFieldFilters,
			},
		});
	} catch (error) {
		throw new Error(
			`Erreur lors de la création de la carte "${data.name}" : ${error}`,
		);
	}
}

// ─── Réinitialisation par slug ──────────────────────────────────────────────────

// Supprime uniquement la carte et les catégories gérées par ce seed (par slug),
// ainsi que les marqueurs rattachés à ces catégories. Toute autre carte, catégorie
// ou marqueur créé par ailleurs reste intact.
export async function resetCartography(payload: Payload) {
	await payload.delete({
		collection: "maps",
		where: { slug: { equals: mapData.slug } },
	});

	for (const category of mapCategories) {
		const { docs } = await payload.find({
			collection: "map-categories",
			where: { slug: { equals: category.slug } },
			limit: 1,
		});
		const existing = docs[0];
		if (!existing) continue;

		await payload.delete({
			collection: "map-markers",
			where: { category: { equals: existing.id } },
		});
		await payload.delete({
			collection: "map-categories",
			where: { id: { equals: existing.id } },
		});
	}
}

// ─── Export ────────────────────────────────────────────────────────────────────

export async function seedCartography(payload: Payload) {
	// 1. Créer les catégories
	const categoryIds: number[] = [];
	for (const category of mapCategories) {
		const id = await createMapCategory(payload, category);
		categoryIds.push(id);
	}

	const [craCategoryId, mdphCategoryId] = categoryIds;

	// 2. Créer les marqueurs CRA
	if (craCategoryId === undefined) {
		throw new Error(
			"Impossible de créer les marqueurs CRA : catégorie introuvable.",
		);
	}
	for (const marker of craMarkers) {
		await createMapMarker(payload, marker, craCategoryId);
	}

	// 3. Créer les marqueurs MDPH
	if (mdphCategoryId === undefined) {
		throw new Error(
			"Impossible de créer les marqueurs MDPH : catégorie introuvable.",
		);
	}
	for (const marker of mdphMarkers) {
		await createMapMarker(payload, marker, mdphCategoryId);
	}

	// 4. Créer la carte (avec les deux catégories + filtre custom field CRA)
	await createMap(payload, mapData, categoryIds, [
		{ categoryId: craCategoryId, key: "pole-adulte" },
	]);
}
